name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      # --- Checkout code ---
      - name: Check out code
        uses: actions/checkout@v4

      # --- Set up Go ---
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      # --- Build app ---
      - name: Build application
        run: ./scripts/buildprod.sh

      # --- Authenticate to Google Cloud ---
      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # --- Set up gcloud CLI ---
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      # --- Test gcloud ---
      - name: Use gcloud CLI
        run: gcloud info
        
      # --- Deploy to Cloud Run ---
      - name: Deploy to Cloud Run
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-480603/notely-ar-repo/notely:latest .
